version: '3.9'
services:
  app:
    build: ./
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
     # - /usr/src/app/node_modules
     # - node_modules:/usr/src/app/node_modules
    env_file: .env
    command: sh -c "${CONTAINER_APP_CMD}"
    ports:
      - "3001:3000"
    networks:
      - bg-service
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - maria-data:/data/db
    env_file: .env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    container_name: database
    networks:
      - bg-service

networks:
  bg-service:
    driver: bridge

volumes:
  maria-data:
    driver: local
